//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_SkinFoodEntities : DbContext
    {
        public DB_SkinFoodEntities()
            : base("name=DB_SkinFoodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<LoaiSP> LoaiSPs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhapHang> NhapHangs { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThuocTinhMyPham> ThuocTinhMyPhams { get; set; }
        public virtual DbSet<ThuongHieu> ThuongHieux { get; set; }
        public virtual DbSet<XuatKho> XuatKhoes { get; set; }
        public virtual DbSet<LienHe> LienHes { get; set; }
    
        public virtual int sp_CapNhatTonKho(Nullable<int> maSP, Nullable<int> soLuongNhap)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var soLuongNhapParameter = soLuongNhap.HasValue ?
                new ObjectParameter("SoLuongNhap", soLuongNhap) :
                new ObjectParameter("SoLuongNhap", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTonKho", maSPParameter, soLuongNhapParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_DonHang_Insert(Nullable<int> maND, Nullable<decimal> tongTien, string diaChiGiaoHang)
        {
            var maNDParameter = maND.HasValue ?
                new ObjectParameter("MaND", maND) :
                new ObjectParameter("MaND", typeof(int));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(decimal));
    
            var diaChiGiaoHangParameter = diaChiGiaoHang != null ?
                new ObjectParameter("DiaChiGiaoHang", diaChiGiaoHang) :
                new ObjectParameter("DiaChiGiaoHang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_DonHang_Insert", maNDParameter, tongTienParameter, diaChiGiaoHangParameter);
        }
    
        public virtual ObjectResult<sp_DonHang_SelectAll_Result> sp_DonHang_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DonHang_SelectAll_Result>("sp_DonHang_SelectAll");
        }
    
        public virtual int sp_DonHang_Update(Nullable<int> maDH, string trangThaiThanhToan)
        {
            var maDHParameter = maDH.HasValue ?
                new ObjectParameter("MaDH", maDH) :
                new ObjectParameter("MaDH", typeof(int));
    
            var trangThaiThanhToanParameter = trangThaiThanhToan != null ?
                new ObjectParameter("TrangThaiThanhToan", trangThaiThanhToan) :
                new ObjectParameter("TrangThaiThanhToan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DonHang_Update", maDHParameter, trangThaiThanhToanParameter);
        }
    
        public virtual int sp_DuyetDanhGia(Nullable<int> maDG, string traLoi)
        {
            var maDGParameter = maDG.HasValue ?
                new ObjectParameter("MaDG", maDG) :
                new ObjectParameter("MaDG", typeof(int));
    
            var traLoiParameter = traLoi != null ?
                new ObjectParameter("TraLoi", traLoi) :
                new ObjectParameter("TraLoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DuyetDanhGia", maDGParameter, traLoiParameter);
        }
    
        public virtual int sp_NguoiDung_Create(string hoTen, string soDienThoai, string tenDangNhap, string matKhau)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NguoiDung_Create", hoTenParameter, soDienThoaiParameter, tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int sp_NguoiDung_ChangePassword(string tenDangNhap, string matKhauCu, string matKhauMoi)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauCuParameter = matKhauCu != null ?
                new ObjectParameter("MatKhauCu", matKhauCu) :
                new ObjectParameter("MatKhauCu", typeof(string));
    
            var matKhauMoiParameter = matKhauMoi != null ?
                new ObjectParameter("MatKhauMoi", matKhauMoi) :
                new ObjectParameter("MatKhauMoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NguoiDung_ChangePassword", tenDangNhapParameter, matKhauCuParameter, matKhauMoiParameter);
        }
    
        public virtual ObjectResult<sp_NguoiDung_Login_Result> sp_NguoiDung_Login(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NguoiDung_Login_Result>("sp_NguoiDung_Login", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int sp_SanPham_Delete(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SanPham_Delete", maSPParameter);
        }
    
        public virtual int sp_SanPham_Insert(string tenSP, Nullable<decimal> giaBan, Nullable<int> soLuongTon, Nullable<int> maDM, Nullable<int> maTH, Nullable<int> maLoai)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(decimal));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            var maDMParameter = maDM.HasValue ?
                new ObjectParameter("MaDM", maDM) :
                new ObjectParameter("MaDM", typeof(int));
    
            var maTHParameter = maTH.HasValue ?
                new ObjectParameter("MaTH", maTH) :
                new ObjectParameter("MaTH", typeof(int));
    
            var maLoaiParameter = maLoai.HasValue ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SanPham_Insert", tenSPParameter, giaBanParameter, soLuongTonParameter, maDMParameter, maTHParameter, maLoaiParameter);
        }
    
        public virtual ObjectResult<sp_SanPham_SelectAll_Result> sp_SanPham_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SanPham_SelectAll_Result>("sp_SanPham_SelectAll");
        }
    
        public virtual int sp_SanPham_Update(Nullable<int> maSP, string tenSP, Nullable<decimal> giaBan, Nullable<int> soLuongTon)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(decimal));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SanPham_Update", maSPParameter, tenSPParameter, giaBanParameter, soLuongTonParameter);
        }
    
        public virtual int sp_ThanhToanDonHang(Nullable<int> maDH, string phuongThuc)
        {
            var maDHParameter = maDH.HasValue ?
                new ObjectParameter("MaDH", maDH) :
                new ObjectParameter("MaDH", typeof(int));
    
            var phuongThucParameter = phuongThuc != null ?
                new ObjectParameter("PhuongThuc", phuongThuc) :
                new ObjectParameter("PhuongThuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThanhToanDonHang", maDHParameter, phuongThucParameter);
        }
    
        public virtual int sp_ThemDonHang(Nullable<int> maND, Nullable<int> maSP, Nullable<int> soLuong, string diaChiGiaoHang)
        {
            var maNDParameter = maND.HasValue ?
                new ObjectParameter("MaND", maND) :
                new ObjectParameter("MaND", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var diaChiGiaoHangParameter = diaChiGiaoHang != null ?
                new ObjectParameter("DiaChiGiaoHang", diaChiGiaoHang) :
                new ObjectParameter("DiaChiGiaoHang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDonHang", maNDParameter, maSPParameter, soLuongParameter, diaChiGiaoHangParameter);
        }
    
        public virtual int sp_ThemSanPham(string tenSP, Nullable<decimal> giaBan, Nullable<int> soLuongTon, Nullable<int> maDM, Nullable<int> maTH, Nullable<int> maLoai)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(decimal));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            var maDMParameter = maDM.HasValue ?
                new ObjectParameter("MaDM", maDM) :
                new ObjectParameter("MaDM", typeof(int));
    
            var maTHParameter = maTH.HasValue ?
                new ObjectParameter("MaTH", maTH) :
                new ObjectParameter("MaTH", typeof(int));
    
            var maLoaiParameter = maLoai.HasValue ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemSanPham", tenSPParameter, giaBanParameter, soLuongTonParameter, maDMParameter, maTHParameter, maLoaiParameter);
        }
    }
}
