//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapHang
    {
        public int MaNhap { get; set; }
        public int MaSP { get; set; }
        public int SoLuongNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NhaCungCap { get; set; }
        public Nullable<decimal> GiaVon { get; set; }
        public string GhiChu { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
