//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatKho
    {
        public int MaXuat { get; set; }
        public int MaSP { get; set; }
        public int SoLuongXuat { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string LyDoXuat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
